# Generated by Django 4.0.4 on 2022-04-16 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_restaurant_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='VoteByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('selected_menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.menu')),
            ],
        ),
    ]
