# Generated by Django 4.0.4 on 2022-04-17 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_menu_vote_count_votebyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='votebyuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2008-09-03T20:56:35.450686Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votebyuser',
            name='created_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='votebyuser',
            unique_together={('selected_menu', 'date', 'created_by')},
        ),
    ]
