# Generated by Django 4.0.4 on 2022-04-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_menu_vote_count_votebyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='votebyuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=10.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votebyuser',
            name='created_by',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='votebyuser',
            unique_together={('selected_menu', 'date', 'created_by')},
        ),
    ]
