# Generated by Django 4.0.4 on 2022-04-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_votebyuser_created_at_votebyuser_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_menu', models.IntegerField()),
                ('restaurant_id', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('restaurant_id', 'date')},
            },
        ),
    ]
