# Generated by Django 4.0.4 on 2022-04-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_winnerrestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnerrestaurant',
            name='menus',
            field=models.CharField(default='menus', max_length=250),
        ),
    ]
