# Generated by Django 4.0.4 on 2022-04-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_winnerrestaurant_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnerrestaurant',
            name='restaurant_name',
            field=models.CharField(default='restaurant_name', max_length=100),
        ),
    ]
