# Generated by Django 4.0.4 on 2022-04-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_winnerrestaurant_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
